### PR TITLE
Brave compose

### PR DESCRIPTION
**Pull request by Szubie**
Add a new `brave compose` command which reads a brave-compose.yml file and spins up the system of containers defined in it. Defining the system in one place like this makes it much easier to see/manage large deployments made up of multiple containers. In addition, it allows for a higher level of abstraction by thinking of multiple containers as a single deployment.

## Integration with Bravefiles
`brave-compose.yaml` files integrate well with the existing Bravefiles, allowing the option for default unit settings to be loaded from bravefiles. This allows for the `brave-compose.yaml` file to remain lean and provide a high-level overview of the system. Settings specified in the `brave-compose.yaml` file will override those in the provided Bravefile (if any).

## Optional Build
Although the focus of the compose tool is on deployment, there is also an optional build flag in the `brave-compose.yaml` file allowing for users to build entire systems and deploy them in a single command. All units and images from a build will be cleaned up if an issue is encountered, encouraging treating the set of containers as a single entity.

## Changes to bravetools
To make these changes I narrowed the scope of the deployment functions `InitUnit` and `Postdeploy` to accept `shared.Service` structs instead of the whole Bravefile. This change mostly has no effect, but one thing does change - currently the Base unit name name is stored in the DB in UnitData. After this change, the actual Image the unit was derived from name will stored instead. This actually makes more sense to me - multiple images could be based on the same base unit, so it's more important to store the actual image a unit is deployed from.

## TODO
- ~~Example script with example compose.yaml file~~
- ~~Documentation still needs to be added~~
- ~~Dependencies between units to determine deployment order~~

### CODE REVIEW

**Comment by adrozdovbering** [comment]
Hi Ben. It would be very useful to have a test `brave-compose.yml` file and a test script in `test` folder. Could you please add them. Thank you!

**Comment by Szubie** [comment]
> Hi Ben. It would be very useful to have a test `brave-compose.yml` file and a test script in `test` folder. Could you please add them. Thank you!

I am still working on a reproducible script and brave-compose.yml to show an example of the compose command in action, will add them when possible.

Just as a quick update I've added support for dependencies between services in the compose file - the services will be topologically ordered to ensure that each service is built after the services it depends on. Tests for the topological ordering pass, so it appears to work as expected - let me know if I missed any cases.

**Comment by Szubie** [comment]
### Switching build/deploy directory
A further update: I realized that the majority of service Bravefiles will be written from an individual per-component basis and will rely on copying resources into containers from the local dir of that service. When composing these individual components together from a higher directory the relative paths would be incorrect.

To address this, `brave compose` now by default switches into the directory containing the Bravefile of the service if that is provided when building and deploying an image. This should be the most common case and so should prioritised. If for some reason that needs to be overriden, the new "context" field allows users to define a different working directory for building/deploying on a per-service basis.

This behaviour of switching the build/deploy working directory to that of the Bravefile perhaps could be extended to the other brave `build` and `deploy` commands as it seems a sensible default.

### Next steps
While working on reproducible examples for `brave compose` I ran into the following blocking issues:
- Difficulties detaching from a server process if starting that service in Postdeploy `Run` command. Without detaching, deploy will stop on the first server started. But attempting to start a process in the background that keeps running was hard.
- Passing environment variables into containers before running commands was also a problem.

The first problem is much more severe, as it essentially blocks the use of Compose for spinning up multiple servers. The second is less serious but could probably be addressed along with the first. The primary issue seems to be with how the LXD client (lxc) is sending commands currently in bravetools. I have some ideas on how to make the above cases work with a few additions/changes to command execution.

**Comment by Szubie** [comment]
Updates:

### Skip build phase for existing images
Recent additions to bravetools now [raise an error if an image already exists](https://github.com/bravetools/bravetools/pull/113). I've updated brave compose to handle this in what I think is the best way for the tool.

If a service's "build" field is set to true and the image already exists, compose will skip building the image and continue with the rest of the compose operations (deploy etc.). This makes it easy to leave the build flag set to true in the compose file regardless of the state of the system, with it acting as a "build if image doesn't exist" flag. This seems better than the alternative (requiring manually tweaking the compose file to turn off build after first building the images).

### "base" field within compose file

This one is speculative, but thought it was worth considering. Sometimes several images might share the same base dependencies, and it would be nice to be able to reuse the same base image as a starting point. It is already possible to first build a base image and have other builds import that local image, but it's a hassle to do and relies on the existing state of the system.

The base field makes this kind of thing possible within a compose file. A service with "base" set to true is not deployed, only built. In addition, since it is primarily a way of accelerating builds, by default a "base" image will automatically be cleaned up after a build - but if you want to keep it, you may set the "build" field to true. Services that depend on the base image can import it as a local image in their Bravefiles - in the compose file they can also express their dependency on the base image.

If every image depending on a base image already exists, the base image build will also be skipped as it is not required.

An example using the base idea to reuse a base image between 3 services has been added to the examples folder - let me know if you think this is worth adding.

**Comment by adrozdovbering** [comment]
This is where I think that compose shouldn't be about. "build", but rather, about "create a new unit based on image and then stand up the system". It feels like having image build and compose declared in one place mixes different concepts. Here's what I thought originally:
1. define and build an image. Image can be a) a simple OS, b) prebuilt packages, c) custom built application
Images are stored in the local or remote repository. Image can have different versions.

2. Use image from repository as-it-is or modify it as needed for deployment. This is where "post-deploy" declarations are coming in. This can be declared in "compose" to build a custom system.

3. There's option "publish" which can export newly customised and deployed unit as a brand new image that can be used in the future as "a base".


Last thought - having various flags, in my opinion, would bring unnecessary complexity and might lead to more complex logic in the Bravetools code.

What do you think?

**Pull request merged**
